// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tubjjcfakjifgdeloaqu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR1YmpqY2Zha2ppZmdkZWxvYXF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzMDY3NTYsImV4cCI6MjA1Nzg4Mjc1Nn0.phU543wRu602qE7qI-icWMx07i1VULSz7Uk_0VvYXXY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});