// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tubjjcfakjifgdeloaqu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR1YmpqY2Zha2ppZmdkZWxvYXF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzMDY3NTYsImV4cCI6MjA1Nzg4Mjc1Nn0.phU543wRu602qE7qI-icWMx07i1VULSz7Uk_0VvYXXY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const baseClient = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Tablas cuyas consultas deben enrutarse al schema `iniciativas`.
// `user_roles`, `profiles`, `companies`, `countries` existen en AMBOS schemas;
// se mantienen apuntando a `public` (comportamiento por defecto) porque el
// resto de la app ya funciona con esas.
const INICIATIVAS_TABLES = new Set<string>([
  'initiatives',
  'favorites',
  'notifications',
  'community_posts',
  'community_comments',
  'community_reactions',
  'library_resources',
  'accompaniment_requests',
  'module_permissions',
]);

// Proxy para enrutar `from()` al schema correcto sin tocar el resto del API.
export const supabase: SupabaseClient<Database> = new Proxy(baseClient, {
  get(target, prop, receiver) {
    if (prop === 'from') {
      return (table: string) => {
        if (INICIATIVAS_TABLES.has(table)) {
          // @ts-ignore - schema tipado solo para schemas declarados
          return (target as any).schema('iniciativas').from(table);
        }
        return target.from(table as any);
      };
    }
    return Reflect.get(target, prop, receiver);
  },
}) as SupabaseClient<Database>;
